apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
  annotations:
    {}
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-speedtest
  namespace: speedtest
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-speedtest
  template:
    metadata:
      labels:
        app: speedtest
        workload.user.cattle.io/workloadselector: apps.deployment-default-speedtest
      namespace: speedtest
    spec:
      containers:
        - imagePullPolicy: Always
          name: speedtest
          securityContext:
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            privileged: false
            allowPrivilegeEscalation: false
          _init: false
          image: henrywhitaker3/speedtest-tracker
          env:
            - name: OOKLA_EULA_GDPR
              value: 'true'
          __active: true
