apiVersion: v1
kind: Service
metadata:
  name: speedtest-service
  annotations:
    {}
  labels:
    {}
  namespace: speedtest
spec:
  selector:
    app: speedtest
  ports:
    - name: speedtestport
      port: 8765
      protocol: TCP
      targetPort: 80
  sessionAffinity: None
  type: NodePort
__clone: true
