apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptimekuma-ingress
  annotations:
    {}
  labels:
    {}
  namespace: uptimekuma
spec:
  ingressClassName: nginx2
  rules:
  - host: uptime.homelab.us
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: uptimekuma-service
            port:
              number: 3001
  tls:
  backend:
    {}
__clone: true
cacheObject:
  useNestedBackendField: true
  showPathType: true
